# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180702_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(null=True),
        ),
    ]
