# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
